#define TH1_REV "230" 
#define TH2_REVISION 0 
#define TH1_REVISION '1230' 
#ifdef TH1 
#define THE_HELL_VERSION_INT 1,230,0,0 
#define THE_HELL_VERSION_STRING "1.230.0" 
#else 
#define THE_HELL_VERSION_INT 0,0,0 
#define THE_HELL_VERSION_STRING "v0.0" 
#endif 
#define THE_HELL_VERSION_HUMAN_STRING PRJ_NAME " " THE_HELL_VERSION_STRING 
