macro (LIBRARY)
	IF(${ARGC} EQUAL 0)
		message(FATAL_ERROR "NAME should be specified for the Library")
	ENDIF()
	SET(__is_library TRUE)
	SET(__current_target_name "lib${ARGV0}")
	
	IF ((${ARGC} GREATER 1) AND  (NOT ("@${ARGV1}@" EQUAL "@@")))
		LIST(APPEND __alowed_types STATIC SHARED MODULE)
		LIST(FIND __alowed_types ${ARGV1} __type_is_allowed)
		IF (__type_is_allowed EQUAL -1)
			message(FATAL_ERROR "Specified library type is not allowed: ${TYPE}")
		ELSE()
			SET(__lib_type ${ARGV1})
		ENDIF()
		UNSET(__alowed_types)
		UNSET(__type_is_allowed)
	ELSE()
		SET(__lib_type STATIC)
	ENDIF()
	
	add_library(${__current_target_name} ${__lib_type} "")
	STORE_TARGET_PATH(${__current_target_name} ${CMAKE_CURRENT_SOURCE_DIR})
	
endmacro()